# max_mind_db_path = "<path to GeoLite2-City.mmdb>"
# cloud_provider_cidr_db_path = "<path to cidrs.csv>"

name = "ipfs"
bootnodes = ["/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"]
disjoint_query_paths = false
noise_legacy = false
